import { JsonFormsRendererRegistryEntry } from '@jsonforms/core';
import {
  ActionLevelSourceAPIControlRenderer,
  ActionLevelSourceAPIControlTester,
  ButtonControlRenderer,
  ButtonControlTester,
  CalibrationInstrumentsControlRenderer,
  CalibrationInstrumentsControlTester,
  CanvasControlRenderer,
  CanvasControlTester,
  DynamicApiControlRenderer,
  DynamicApiControlTester,
  DynamicControlWithOtherRenderer,
  DynamicControlWithOtherTester,
  DynamicMultiSelectControlWithOtherRenderer,
  DynamicMultiSelectControlWithOtherTester,
  FileUploadControl,
  FileUploadControlTester,
  HazardListControlRenderer,
  HazardListControlTester,
  HazardListSelectControlRenderer,
  HazardListSelectControlTester,
  HearingProtectionControlRenderer,
  HearingProtectionControlTester,
  InputWithAdornmentControl,
  InputWithAdornmentControlTester,
  InstrumentsControlRenderer,
  InstrumentsControlTester,
  materialCategorizationStepperRenderer,
  materialCategorizationStepperTester,
  MultiCheckboxRenderer,
  MultiCheckboxTester,
  MultiTextControlRenderer,
  MultiTextControlTester,
  NumberControlRenderer,
  NumberControlTester,
  OelSourceAPIControlRenderer,
  OelSourceAPIControlTester,
  OneOfEnumControlRenderer,
  OneOfEnumControlTester,
  OneOfItemsControlRenderer,
  OneOfItemsControlTester,
  OneOfRadioGroupControlRenderer,
  OneOfRadioGroupControlTester,
  RadioEnumControlRenderer,
  RadioEnumControlTester,
  RadioObjectControl,
  RadioObjectControlTester,
  SampleMediaControlRenderer,
  SampleMediaControlTester,
  ScenarioHazardsControlRenderer,
  ScenarioHazardsControlTester,
  SingleHazardControlRenderer,
  SingleHazardControlTester,
  TextControlRenderer,
  TextControlTester,
  TimeControlRenderer,
  TimeControlTester,
  UnitAPIControlRenderer,
  UnitAPIControlTester,
  WeldingControlDevelopRenderer,
  WeldingControlDevelopTester,
  WeldingControlRenderer,
  WeldingControlTester,
  DynamicMultiControlWithOtherTester,
  DynamicMultiControlWithOtherRenderer,
  RespiratorControlTester,
  RespiratorControlRenderer,
} from './lib/controls';

export { BaseInputControl } from './lib/controls';
export * from './lib/controls';
export * from './lib/widgets';
export * from './lib/api';

export const extraRenderers: JsonFormsRendererRegistryEntry[] = [
  {
    tester: InputWithAdornmentControlTester,
    renderer: InputWithAdornmentControl,
  },
  {
    tester: RadioObjectControlTester,
    renderer: RadioObjectControl,
  },
  { tester: FileUploadControlTester, renderer: FileUploadControl },
  { tester: CanvasControlTester, renderer: CanvasControlRenderer },
  { tester: OneOfEnumControlTester, renderer: OneOfEnumControlRenderer },
  { tester: TimeControlTester, renderer: TimeControlRenderer },
  { tester: TextControlTester, renderer: TextControlRenderer },
  { tester: MultiTextControlTester, renderer: MultiTextControlRenderer },
  { tester: ButtonControlTester, renderer: ButtonControlRenderer },
  {
    tester: materialCategorizationStepperTester,
    renderer: materialCategorizationStepperRenderer,
  },
  { tester: HazardListControlTester, renderer: HazardListControlRenderer },
  {
    tester: HazardListSelectControlTester,
    renderer: HazardListSelectControlRenderer,
  },
  {
    tester: ScenarioHazardsControlTester,
    renderer: ScenarioHazardsControlRenderer,
  },
  {
    tester: DynamicControlWithOtherTester,
    renderer: DynamicControlWithOtherRenderer,
  },
  {
    tester: DynamicMultiControlWithOtherTester,
    renderer: DynamicMultiControlWithOtherRenderer,
  },
  { tester: NumberControlTester, renderer: NumberControlRenderer },
  { tester: DynamicApiControlTester, renderer: DynamicApiControlRenderer },
  { tester: InstrumentsControlTester, renderer: InstrumentsControlRenderer },
  {
    tester: CalibrationInstrumentsControlTester,
    renderer: CalibrationInstrumentsControlRenderer,
  },
  { tester: SampleMediaControlTester, renderer: SampleMediaControlRenderer },
  {
    tester: WeldingControlTester,
    renderer: WeldingControlRenderer,
  },
  {
    tester: WeldingControlDevelopTester,
    renderer: WeldingControlDevelopRenderer,
  },
  {
    tester: OneOfRadioGroupControlTester,
    renderer: OneOfRadioGroupControlRenderer,
  },
  {
    tester: MultiCheckboxTester,
    renderer: MultiCheckboxRenderer,
  },
  {
    tester: HearingProtectionControlTester,
    renderer: HearingProtectionControlRenderer,
  },
  {
    tester: RespiratorControlTester,
    renderer: RespiratorControlRenderer,
  },
  {
    tester: DynamicMultiSelectControlWithOtherTester,
    renderer: DynamicMultiSelectControlWithOtherRenderer,
  },
  {
    tester: OneOfItemsControlTester,
    renderer: OneOfItemsControlRenderer,
  },
  {
    tester: RadioEnumControlTester,
    renderer: RadioEnumControlRenderer,
  },
  {
    tester: OelSourceAPIControlTester,
    renderer: OelSourceAPIControlRenderer,
  },
  {
    tester: ActionLevelSourceAPIControlTester,
    renderer: ActionLevelSourceAPIControlRenderer,
  },
  {
    tester: UnitAPIControlTester,
    renderer: UnitAPIControlRenderer,
  },
  {
    tester: SingleHazardControlTester,
    renderer: SingleHazardControlRenderer,
  },
];
